export const CHECK_GAME_PIN_REQUEST = 'CHECK_GAME_PIN_REQUEST';
export const CHECK_GAME_PIN_SUCCESS = 'CHECK_GAME_PIN_SUCCESS';
export const CHECK_GAME_PIN_FAILURE = 'CHECK_GAME_PIN_FAILURE';

export const CHECK_USERNAME_REQUEST = 'CHECK_USERNAME_REQUEST';
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS';
export const CHECK_USERNAME_FAILURE = 'CHECK_USERNAME_FAILURE';

export const UPDATE_PLAYER_LIST = 'UPDATE_PLAYER_LIST';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';

export const QUESTION_INTRO = 'QUESTION_INTRO';
export const QUESTION_START = 'QUESTION_START';
export const QUESTION_END = 'QUESTION_END';
export const GAME_OVER = 'GAME_OVER';
